#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely; reacts to SIGTERM with a message

# Trap SIGTERM and print "I am invincible!!!"
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
