#!/usr/bin/env bash
# Infinite loop that reacts to SIGTERM

# Flush output immediately and handle SIGTERM
trap 'printf "I am invincible!!!\n"' SIGTERM

while true; do
    printf "To infinity and beyond\n"
    sleep 2
done
